#!/bin/bash

# reapply wallpaper
~/.fehbg

# notification about switching modes
notify-send "Switched to $AUTORANDR_CURRENT_PROFILE mode" -i /usr/share/icons/Papirus-Dark/32x32/status/laptop-trusted.svg

