#!/usr/bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
nm-applet &
unclutter --timeout 10 &
clipmenud &
xss-lock -- slock &
xautolock -time 5 -locker slock &
setxkbmap -option 'grp:caps_toggle' &
$HOME/.fehbg &
picom --config $HOME/.config/picom/picom.conf &

xfsettingsd &
xfce4-power-manager --daemon &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

