#!/bin/bash
# Dmenu shutdown/lock/suspend/reboot menu.
wm=$(echo $XDG_SESSION_TYPE)

if [ $wm == 'wayland' ]; then
    menu='bemenu'
else
    menu='dmenu'
fi

output=$(echo -e "lock\nlogout\nsuspend\nshutdown\nreboot" | $menu -p "ACTION:")

case "$output" in
    logout)
        if [ "$wm" == "i3" ]; then
            i3-msg exit
        elif [ "$wm" == "dwm" ]; then
            killall -9 dwm
        fi
    ;;
    shutdown)
        shutdown -h now
    ;;
    reboot)
        reboot
    ;;
    suspend)
        systemctl suspend
    ;;
    lock)
        if [ $wm == 'wayland' ]; then
            swaylock -K -c 0f1117
        else
            slock
        fi
    ;;
esac
