#!/bin/bash
# Dmenu shutdown/lock/suspend/reboot menu.
#menu='dmenu'
menu='rofi -dmenu --no-show-icons'
output=$(printf "lock\nsuspend\nshutdown\nlogout" | $menu -p "ACTION")

case "$output" in
    logout)
        # i3-msg exit
        swaymsg exit
    ;;
    shutdown)
        shutdown -h now
    ;;
    suspend)
        systemctl suspend
    ;;
    lock)
        # /home/gkeep/scripts/lock.sh
        swaylock -f
    ;;
esac
