#!/usr/bin/bash
# script to update specified dotfiles to your repo's location

export REPO_LOCATION="$HOME/Projects/dotfiles" # your dotfiles repo location here

# to add a file/folder specify its locaion using $HOME or $XDG_CONFIG_HOME here
declare -a FILES=(
    $HOME/.config/dunst \
    $HOME/.config/i3 \
    $HOME/.config/kitty \
    $HOME/.config/nvim \
    $HOME/.config/picom \
    $HOME/.config/polybar \
    $HOME/.profile \
    $HOME/.vimrc \
    $HOME/.zshrc \
    $HOME/.tmux.conf \
    $HOME/.gitconfig \
)

declare -a BLOCK=(
    $HOME/.config/ncmpcpp/error.log \
    $HOME/.config/nvim/colorscheme.vim \
    $HOME/.config/polybar/fonts \
)

for i in "${FILES[@]}"
do
    if [[ $i == *".config"* ]]
    then
        for b in "${BLOCK[@]}"
        do
            if [[ ! $i =~ $b ]]
            then
                rsync -rl $i $REPO_LOCATION/.config
            fi
        done
        echo "Successfully updated $i"
    else
        rsync -rl $i $REPO_LOCATION
    fi
done
