#!/usr/bin/bash
# script to update specified dotfiles to your repo's location

export REPO_LOCATION="$HOME/git/dotfiles" # your dotfiles repo location here

# to add a file/folder specify its locaion using $HOME or $XDG_CONFIG_HOME here
declare -a FILES=(
    $HOME/.config/dunst \
    $HOME/.config/i3 \
    $HOME/.config/i3status \
    $HOME/.config/nvim \
    $HOME/.config/picom \
    $HOME/.config/zsh \
    $HOME/.aliases \
    $HOME/.profile \
    $HOME/.vimrc \
    $HOME/.zshrc \
    $HOME/.tmux.conf \
    $HOME/.gitconfig \
)

declare -a IGNORE=(
    $HOME/.config/ncmpcpp/error.log \
)

for i in "${FILES[@]}"
do
    if [[ $i == *".config"* ]]
    then
        for b in "${IGNORE[@]}"
        do
            if [[ ! $i =~ $b ]]
            then
                rsync -rl $i $REPO_LOCATION/.config
            fi
        done
        echo "Successfully updated $i"
    else
        rsync -rl $i $REPO_LOCATION
    fi
done
